{
 "title": "ZF-Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Firewall Activity Volume",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (dest_port) (count_over_time({job=\"zbf_firewall\"} | json [$__range]))"
    }
   ]
  },
  {
   "title": "Attack Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"zbf_firewall\"}[1m]))"
    }
   ]
  },
  {
   "title": "Top Attacking IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (src_ip) (count_over_time({job=\"zbf_firewall\"} | json [$__range]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"zbf_firewall\"} | json | line_format \"🚨 {{.oob_prefix}} -> IP Atacante: {{.src_ip}} atacó el puerto {{.dest_port}}\""
    }
   ]
  }
 ]
}