# Path to the main ulogd log file.
# This file stores internal ulogd messages, errors, and operational logs
[global]
logfile="/var/log/ulogd.log"
loglevel=5
# Processing stack definition:
# NFLOG captures packets from Netfilter logging group 1.
# BASE extracts basic packet metadata.
# IFINDEX adds network interface index information.
# IP2STR converts IP addresses into human-readable string format.
# PRINTFLOW formats packet/flow information.
# JSON exports the processed data in JSON format
stack=log1:NFLOG,base1:BASE,ifi1:IFINDEX,ip2str1:IP2STR,print1:PRINTFLOW,json1:JSON


# NFLOG group number to listen to.
# Firewall rules must send logs to this same NFLOG group.
# Example iptables rule: -j NFLOG --nflog-group 1
[log1]
group=1

# Enables synchronous writing to the output file.
# When enabled, data is written immediately, reducing the risk of log loss
[json1]
sync=1
file="/var/log/ulogd_firewall.json"
