[global]
logfile="/var/log/ulogd.log"
loglevel=5
rmem=131071
bufsize=150000

# Captura NFLOG (grupo 1) -> Convierte datos a string e IPs -> Exporta a JSON
stack=log1:NFLOG,base1:BASE,ifi1:IFINDEX,ip2str1:IP2STR,print1:PRINTFLOW,json1:JSON

[log1]
group=1

[json1]
sync=1
file="/var/log/ulogd_firewall.json"