/*
 * External crate import.
 *
 * Serde's Deserialize trait allows the program to automatically convert
 * JSON data into Rust data structures.
 * HashMap is used to store firewall zones as key-value pairs.
 * File is used to open the JSON configuration file.
 * Read and Write are used to read file contents and send data to nftables.
 * Command and Stdio are used to execute the nft command and communicate with it
 * through standard input, output, and error streams.
 */
use serde::Deserialize;
use std::collections::HashMap;
use std::fs::File;
use std::io::{Read, Write};
use std::process::{Command, Stdio};

/*
 * Firewall configuration structure.
 *
 * This structure represents the expected format of the JSON configuration file
 * located at config/zones_config.json.
 *
 * The 'zones' field maps each firewall zone name to a list of network interfaces.
 * The 'blocked_ports' field contains TCP ports that should be blocked by the firewall.
 */

#[derive(Deserialize, Debug)]
struct FirewallConfig {
    zones: HashMap<String, Vec<String>>,
    blocked_ports: Vec<u16>,
}

  /*
     * Privilege validation.
     *
     * Modifying Linux Netfilter/nftables rules requires root privileges.
     * The program checks the current user ID using libc::getuid().
     * If the UID is not 0, the program stops and asks the user to run it with sudo.
     */

fn main() {
    if unsafe { libc::getuid() } != 0 {
        eprintln!("[-] Critical Error: This software requires root privileges. Run it with 'sudo'.");
        std::process::exit(1);
    }

   
 /*
     * Configuration file loading.
     *
     * The program opens the JSON configuration file and reads its full content
     * into a string. This content will later be parsed into the FirewallConfig
     * structure.
     */

    let config_path = "config/zones_config.json";
    let mut file = File::open(config_path)
        .expect("[-] Could not open config/zones_config.json. Make sure the file exists.");
    
    let mut json_contents = String::new();
    file.read_to_string(&mut json_contents).unwrap();
    
    let config: FirewallConfig = serde_json::from_str(&json_contents)
        .expect("[-] Error: The configuration JSON file format is invalid.");

    
 // 3. DYNAMIC NFTABLES RULESET GENERATION
    // Starts building the nftables ruleset as a String.
    // The table type 'inet' supports both IPv4 and IPv6.
    // 'flush ruleset' removes previous nftables rules before applying the new one
    
    let mut nft_ruleset = String::from("#!/usr/sbin/nft -f\nflush ruleset\n\ntable inet zbf_infra {\n");

    
    for (zone_name, interfaces) in &config.zones {
        let ifaces_str = interfaces.iter()
            .map(|i| format!("\"{}\"", i))
            .collect::<Vec<String>>()
            .join(", ");
        nft_ruleset.push_str(&format!(
            "    set z_{} {{ type ifname; elements = {{ {} }} }}\n", 
            zone_name.to_lowercase(), 
            ifaces_str
        ));
    }

    
    nft_ruleset.push_str("\n    chain forward {\n        type filter hook forward priority filter; policy drop;\n        \n        # Stateful Inspection: Allow packets from already established connections\n        ct state established,related accept\n");

    
    if !config.blocked_ports.is_empty() {
        let ports_str = config.blocked_ports.iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join(", ");
        
        
        nft_ruleset.push_str(&format!(
            "\n        # Perimeter blocking rules generated by the Rust binary\n\
                     iifname @z_wan tcp dport {{ {} }} log group 1 prefix \"RUST-ZBF-BLOCK\" drop\n", 
            ports_str
        ));
    }

    
    nft_ruleset.push_str("\n        # Default zone logging and implicit drop\n        log group 1 prefix \"RUST-ZBF-DEFAULT-DROP\" drop\n    }\n}\n");

    
// 4. ATOMIC TRANSACTION TO THE LINUX KERNEL
    // Executes the nft command and sends the generated ruleset through STDIN.
    // This avoids writing temporary rule files to disk.

    let mut child = Command::new("nft")
        .args(["-f", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("[-] Failed to communicate with the nftables subsystem.");

    {
        let stdin = child.stdin.as_mut().expect("[-] Could not open the STDIN channel to nftables.");
        stdin.write_all(nft_ruleset.as_bytes()).expect("[-] Error while transmitting the byte stream to the Kernel.");
    }

    let output = child.wait_with_output().unwrap();

    
// 5. TRANSACTION RESULT EVALUATION
    // Checks whether the nft command finished successfully

    if output.status.success() {
        println!("[+] Success: The Rust engine has compiled and atomically applied the zone policies in Netfilter.");
    } else {
        let error_log = String::from_utf8_lossy(&output.stderr);
        eprintln!("[-] Critical error while compiling nftables rules:\n{}", error_log);
    }
}
